-- Gestão Financeira - V1
-- Execute este script no SQL Editor do Supabase antes de configurar os secrets no Streamlit.

create table if not exists public.finance_movements (
    id bigint generated by default as identity primary key,
    movement_date date null,
    description text not null,
    value numeric(14,2) not null default 0,
    category text,
    competence text,
    classification text not null check (classification in ('ENTRADA','SAÍDA')),
    allocation_value numeric(14,2) not null default 0,
    fixed_variable text,
    created_at timestamptz not null default now()
);

create table if not exists public.finance_forecasts (
    id bigint generated by default as identity primary key,
    due_date date null,
    description text not null,
    category text,
    value numeric(14,2) not null default 0,
    adjustment numeric(14,2) not null default 0,
    final_value numeric(14,2) not null default 0,
    type text not null check (type in ('Entrada','Saída')),
    status text not null default 'Não pago',
    simulate_payment boolean not null default false,
    competence text,
    created_at timestamptz not null default now()
);

create table if not exists public.finance_accounts (
    id bigint generated by default as identity primary key,
    name text not null unique,
    balance numeric(14,2) not null default 0,
    updated_at timestamptz not null default now()
);

create table if not exists public.finance_debts (
    id bigint generated by default as identity primary key,
    description text not null,
    total_value numeric(14,2) not null default 0,
    status text,
    total_installments integer not null default 0,
    paid_installments integer not null default 0,
    installment_value numeric(14,2) not null default 0,
    open_value numeric(14,2) not null default 0,
    created_at timestamptz not null default now()
);

create table if not exists public.finance_settings (
    id bigint generated by default as identity primary key,
    key text not null unique,
    value numeric(18,4) not null default 0,
    updated_at timestamptz not null default now()
);

create index if not exists idx_finance_movements_competence on public.finance_movements(competence);
create index if not exists idx_finance_forecasts_due_date on public.finance_forecasts(due_date);
create index if not exists idx_finance_forecasts_competence on public.finance_forecasts(competence);

-- V1 simples: as políticas de acesso devem ser definidas de acordo com a chave usada no app.
-- Se utilizar service_role exclusivamente nos secrets do Streamlit, não exponha a chave no código ou no navegador.
